import { type RouteConfig, route, layout } from "@react-router/dev/routes";

export default [
  route("/", "routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("verify-email", "routes/verify-email.tsx"),

  layout("routes/onboarding.tsx", [
    route("onboarding/step1", "routes/onboarding.step1.tsx"),
    route("onboarding/step2", "routes/onboarding.step2.tsx"),
    route("onboarding/step3", "routes/onboarding.step3.tsx"),
  ]),

  layout("routes/dashboard.tsx", [
    route("dashboard", "routes/dashboard.overview.tsx"),
    route("dashboard/analytics", "routes/dashboard.analytics.tsx"),
    route("dashboard/reports", "routes/dashboard.reports.tsx"),
    route("dashboard/settings", "routes/dashboard.settings.tsx"),
    route("dashboard/realtime", "routes/dashboard.realtime.tsx"),
    route("dashboard/metrics", "routes/dashboard.metrics.tsx"),
    route("dashboard/alerts", "routes/dashboard.alerts.tsx"),
    route("dashboard/logs", "routes/dashboard.logs.tsx"),
  ]),

  layout("routes/users.tsx", [
    route("users", "routes/users._index.tsx"),
    route("users/new", "routes/users.new.tsx"),
    route("users/:userId", "routes/users.$userId.tsx"),
    route("users/:userId/edit", "routes/users.$userId.edit.tsx"),
    route("users/:userId/activity", "routes/users.$userId.activity.tsx"),
    route("users/:userId/permissions", "routes/users.$userId.permissions.tsx"),
    route("users/:userId/sessions", "routes/users.$userId.sessions.tsx"),
    route("users/:userId/audit", "routes/users.$userId.audit.tsx"),
    route("users/roles", "routes/users.roles.tsx"),
    route("users/roles/:roleId", "routes/users.roles.$roleId.tsx"),
    route("users/groups", "routes/users.groups.tsx"),
    route("users/invitations", "routes/users.invitations.tsx"),
  ]),

  layout("routes/products.tsx", [
    route("products", "routes/products._index.tsx"),
    route("products/new", "routes/products.new.tsx"),
    route("products/:productId", "routes/products.$productId.tsx"),
    route("products/:productId/edit", "routes/products.$productId.edit.tsx"),
    route("products/:productId/variants", "routes/products.$productId.variants.tsx"),
    route("products/:productId/media", "routes/products.$productId.media.tsx"),
    route("products/:productId/reviews", "routes/products.$productId.reviews.tsx"),
    route("products/:productId/analytics", "routes/products.$productId.analytics.tsx"),
    route("products/categories", "routes/products.categories.tsx"),
    route("products/categories/:catId", "routes/products.categories.$catId.tsx"),
    route("products/collections", "routes/products.collections.tsx"),
    route("products/inventory", "routes/products.inventory.tsx"),
    route("products/pricing", "routes/products.pricing.tsx"),
    route("products/import", "routes/products.import.tsx"),
    route("products/export", "routes/products.export.tsx"),
  ]),

  layout("routes/orders.tsx", [
    route("orders", "routes/orders._index.tsx"),
    route("orders/:orderId", "routes/orders.$orderId.tsx"),
    route("orders/:orderId/tracking", "routes/orders.$orderId.tracking.tsx"),
    route("orders/:orderId/refund", "routes/orders.$orderId.refund.tsx"),
    route("orders/:orderId/notes", "routes/orders.$orderId.notes.tsx"),
    route("orders/:orderId/timeline", "routes/orders.$orderId.timeline.tsx"),
    route("orders/returns", "routes/orders.returns.tsx"),
    route("orders/returns/:returnId", "routes/orders.returns.$returnId.tsx"),
    route("orders/fulfillment", "routes/orders.fulfillment.tsx"),
    route("orders/shipments", "routes/orders.shipments.tsx"),
  ]),

  layout("routes/invoices.tsx", [
    route("invoices", "routes/invoices._index.tsx"),
    route("invoices/:invoiceId", "routes/invoices.$invoiceId.tsx"),
    route("invoices/new", "routes/invoices.new.tsx"),
    route("invoices/:invoiceId/send", "routes/invoices.$invoiceId.send.tsx"),
    route("invoices/recurring", "routes/invoices.recurring.tsx"),
    route("invoices/templates", "routes/invoices.templates.tsx"),
  ]),

  layout("routes/customers.tsx", [
    route("customers", "routes/customers._index.tsx"),
    route("customers/new", "routes/customers.new.tsx"),
    route("customers/:customerId", "routes/customers.$customerId.tsx"),
    route("customers/:customerId/edit", "routes/customers.$customerId.edit.tsx"),
    route("customers/:customerId/orders", "routes/customers.$customerId.orders.tsx"),
    route("customers/:customerId/notes", "routes/customers.$customerId.notes.tsx"),
    route("customers/:customerId/segments", "routes/customers.$customerId.segments.tsx"),
    route("customers/segments", "routes/customers.segments.tsx"),
    route("customers/segments/:segmentId", "routes/customers.segments.$segmentId.tsx"),
    route("customers/import", "routes/customers.import.tsx"),
  ]),

  layout("routes/marketing.tsx", [
    route("marketing/campaigns", "routes/marketing.campaigns.tsx"),
    route("marketing/campaigns/new", "routes/marketing.campaigns.new.tsx"),
    route("marketing/campaigns/:campaignId", "routes/marketing.campaigns.$campaignId.tsx"),
    route("marketing/email", "routes/marketing.email.tsx"),
    route("marketing/email/templates", "routes/marketing.email.templates.tsx"),
    route("marketing/automations", "routes/marketing.automations.tsx"),
    route("marketing/automations/:automationId", "routes/marketing.automations.$automationId.tsx"),
    route("marketing/coupons", "routes/marketing.coupons.tsx"),
    route("marketing/coupons/new", "routes/marketing.coupons.new.tsx"),
    route("marketing/analytics", "routes/marketing.analytics.tsx"),
    route("marketing/seo", "routes/marketing.seo.tsx"),
  ]),

  layout("routes/content.tsx", [
    route("content/pages", "routes/content.pages.tsx"),
    route("content/pages/new", "routes/content.pages.new.tsx"),
    route("content/pages/:pageId", "routes/content.pages.$pageId.tsx"),
    route("content/blog", "routes/content.blog.tsx"),
    route("content/blog/new", "routes/content.blog.new.tsx"),
    route("content/blog/:postId", "routes/content.blog.$postId.tsx"),
    route("content/media", "routes/content.media.tsx"),
    route("content/navigation", "routes/content.navigation.tsx"),
    route("content/redirects", "routes/content.redirects.tsx"),
  ]),

  layout("routes/settings.tsx", [
    route("settings/profile", "routes/settings.profile.tsx"),
    route("settings/account", "routes/settings.account.tsx"),
    route("settings/billing", "routes/settings.billing.tsx"),
    route("settings/billing/plans", "routes/settings.billing.plans.tsx"),
    route("settings/billing/invoices", "routes/settings.billing.invoices.tsx"),
    route("settings/billing/payment-methods", "routes/settings.billing.payment-methods.tsx"),
    route("settings/notifications", "routes/settings.notifications.tsx"),
    route("settings/integrations", "routes/settings.integrations.tsx"),
    route("settings/integrations/:integrationId", "routes/settings.integrations.$integrationId.tsx"),
    route("settings/api-keys", "routes/settings.api-keys.tsx"),
    route("settings/webhooks", "routes/settings.webhooks.tsx"),
    route("settings/webhooks/new", "routes/settings.webhooks.new.tsx"),
    route("settings/webhooks/:webhookId", "routes/settings.webhooks.$webhookId.tsx"),
    route("settings/team", "routes/settings.team.tsx"),
    route("settings/team/:memberId", "routes/settings.team.$memberId.tsx"),
    route("settings/security", "routes/settings.security.tsx"),
    route("settings/security/two-factor", "routes/settings.security.two-factor.tsx"),
    route("settings/security/sessions", "routes/settings.security.sessions.tsx"),
    route("settings/domains", "routes/settings.domains.tsx"),
    route("settings/emails", "routes/settings.emails.tsx"),
    route("settings/shipping", "routes/settings.shipping.tsx"),
    route("settings/taxes", "routes/settings.taxes.tsx"),
    route("settings/checkout", "routes/settings.checkout.tsx"),
    route("settings/localization", "routes/settings.localization.tsx"),
  ]),

  layout("routes/support.tsx", [
    route("support/tickets", "routes/support.tickets.tsx"),
    route("support/tickets/new", "routes/support.tickets.new.tsx"),
    route("support/tickets/:ticketId", "routes/support.tickets.$ticketId.tsx"),
    route("support/knowledge-base", "routes/support.knowledge-base.tsx"),
    route("support/knowledge-base/:articleId", "routes/support.knowledge-base.$articleId.tsx"),
    route("support/chat", "routes/support.chat.tsx"),
  ]),

  layout("routes/reports.tsx", [
    route("reports/sales", "routes/reports.sales.tsx"),
    route("reports/sales/daily", "routes/reports.sales.daily.tsx"),
    route("reports/sales/monthly", "routes/reports.sales.monthly.tsx"),
    route("reports/inventory", "routes/reports.inventory.tsx"),
    route("reports/customers", "routes/reports.customers.tsx"),
    route("reports/custom", "routes/reports.custom.tsx"),
    route("reports/custom/new", "routes/reports.custom.new.tsx"),
    route("reports/custom/:reportId", "routes/reports.custom.$reportId.tsx"),
    route("reports/exports", "routes/reports.exports.tsx"),
  ]),

  layout("routes/admin.tsx", [
    route("admin/system", "routes/admin.system.tsx"),
    route("admin/audit-log", "routes/admin.audit-log.tsx"),
    route("admin/feature-flags", "routes/admin.feature-flags.tsx"),
    route("admin/maintenance", "routes/admin.maintenance.tsx"),
    route("admin/migrations", "routes/admin.migrations.tsx"),
    route("admin/cache", "routes/admin.cache.tsx"),
    route("admin/queues", "routes/admin.queues.tsx"),
    route("admin/workers", "routes/admin.workers.tsx"),
  ]),
] satisfies RouteConfig;
